[versions]
android-compileSdk = "36"
android-gradlePlugin = "9.0.0"
android-minSdk = "24"
android-targetSdk = "36"
android-wear-minSdk = "25"
android-wear-targetSdk = "33"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-benchmark = "1.4.1"
androidx-composeBom = "2026.01.00"
androidx-core = "1.17.0"
androidx-datastore = "1.2.0"
androidx-espresso = "3.7.0"
androidx-glance = "1.1.1"
androidx-hilt = "1.3.0"
androidx-junit = "1.3.0"
androidx-lifecycle = "2.10.0"
androidx-material3AdaptiveNavigation3 = "1.3.0-alpha06"
androidx-navigation = "2.9.6"
androidx-navigation3 = "1.0.0"
androidx-profileinstaller = "1.4.1"
androidx-splashscreen = "1.2.0"
androidx-uiautomator = "2.3.0"
androidx-wear = "1.3.0"
androidx-wearCompose = "1.5.6"
androidx-wearInput = "1.2.0"
androidx-wearToolingPreview = "1.0.0"
google-firebaseBom = "34.8.0"
google-firebaseCrashlytics = "3.0.6"
google-hilt = "2.59"
google-ksp = "2.3.4"
google-ossLicenses = "0.10.10"
google-playServicesOssLicenses = "17.3.0"
google-playServicesWearable = "19.0.0"
google-services = "4.4.4"
gradle-publish = "2.0.0"
jetbrains-compose = "1.10.0"
jetbrains-composeMaterial3 = "1.9.0"
jetbrains-composeMaterialIconsExtended = "1.7.3"
jetbrains-dokka = "2.1.0"
jetbrains-kotlinxCollectionsImmutable = "0.4.0"
jetbrains-kotlinxCoroutines = "1.10.2"
jetbrains-kotlinxDatetime = "0.7.1-0.6.x-compat"
jetbrains-kotlinxSerialization = "1.10.0"
jetbrains-lifecycle = "2.9.6"
junit = "4.13.2"
koin-bom = "4.1.1"
kotlin = "2.3.0"
ktlint = "1.8.0"
mockk = "1.14.9"
mockkCommon = "1.12.5"
sergiobelda-composeVectorize = "1.1.0"
sergiobelda-fonament = "0.0.1-alpha03"
sergiobelda-navigationComposeExtended = "1.5.0"
sergiobelda-pigment = "0.6.0"
sergiobelda-projectconfig = "2026.01.03"
spotless = "8.2.0"
squareup-moshi = "1.15.2"
squareup-okhttp3 = "5.3.2"
squareup-retrofit = "3.0.0"
touchlab-stately = "2.1.0"
vanniktech-mavenpublish = "0.33.0"

[libraries]
## android
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }

## androidx
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macroJunit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "androidx-material3AdaptiveNavigation3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-glance-appWidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-glance = { module = "androidx.glance:glance", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
androidx-hilt-lifecycle-viewmodelCompose = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "androidx-hilt" }
androidx-lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelNavigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-uiautomator" }
androidx-wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wearCompose" }
androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wearCompose" }
androidx-wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wearCompose" }
androidx-wear-input = { module = "androidx.wear:wear-input", version.ref = "androidx-wearInput" }
androidx-wear-toolingPreview = { module = "androidx.wear:wear-tooling-preview", version.ref = "androidx-wearToolingPreview" }
androidx-wear-wear = { module = "androidx.wear:wear", version.ref = "androidx-wear" }

## google
google-dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-dagger-hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebaseBom" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-gms-ossLicensesPlugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "google-ossLicenses" }
google-gms-playServicesOssLicenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "google-playServicesOssLicenses" }
google-gms-playServicesWearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "google-playServicesWearable" }

## jetbrains
jetbrains-androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-compose-animationGraphics = { module = "org.jetbrains.compose.animation:animation-graphics", version.ref = "jetbrains-compose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-composeMaterial3" }
jetbrains-compose-materialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "jetbrains-composeMaterialIconsExtended" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
jetbrains-compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetbrains-compose" }
jetbrains-compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose" }
jetbrains-kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "jetbrains-kotlinxCollectionsImmutable" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-kotlinxCoroutines" }
jetbrains-kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "jetbrains-kotlinxCoroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "jetbrains-kotlinxCoroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrains-kotlinxCoroutines" }
jetbrains-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "jetbrains-kotlinxDatetime" }
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "jetbrains-kotlinxSerialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrains-kotlinxSerialization" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-androidXCompose = { module = "io.insert-koin:koin-androidx-compose" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-composeViewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }

mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }

sergiobelda-composeVectorize-core = { module = "dev.sergiobelda.compose.vectorize:compose-vectorize-core", version.ref = "sergiobelda-composeVectorize" }
sergiobelda-fonament-diKoin = { module = "dev.sergiobelda.fonament:fonament-di-koin", version.ref = "sergiobelda-fonament" }
sergiobelda-fonament-presentation = { module = "dev.sergiobelda.fonament:fonament-presentation", version.ref = "sergiobelda-fonament" }
sergiobelda-navigationComposeExtended = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended", version.ref = "sergiobelda-navigationComposeExtended" }
sergiobelda-navigationComposeExtendedAnnotation = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-annotation", version.ref = "sergiobelda-navigationComposeExtended" }
sergiobelda-navigationComposeExtendedCompiler = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-compiler", version.ref = "sergiobelda-navigationComposeExtended" }
sergiobelda-navigationComposeExtendedWear = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-wear", version.ref = "sergiobelda-navigationComposeExtended" }
sergiobelda-pigment = { module = "dev.sergiobelda.pigment:pigment", version.ref = "sergiobelda-pigment" }

squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "squareup-moshi" }
squareup-moshiKotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "squareup-moshi" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp3" }
squareup-okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-okhttp3" }
squareup-retrofit2-converterKotlinxSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "squareup-retrofit" }
squareup-retrofit2-converterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "squareup-retrofit" }
squareup-retrofit2-converterScalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "squareup-retrofit" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup-retrofit" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

touchlab-stately-concurrentCollections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "touchlab-stately" }

[plugins]
## android
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
android-test = { id = "com.android.test", version.ref = "android-gradlePlugin" }

## google
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebaseCrashlytics" }
google-gms-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }

gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }

## jetbrains
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

sergiobelda-composeVectorize = { id = "dev.sergiobelda.compose.vectorize", version.ref = "sergiobelda-composeVectorize" }
sergiobelda-convention-android-library = { id = "dev.sergiobelda.convention.android.library", version.ref = "sergiobelda-projectconfig" }
sergiobelda-convention-spotless = { id = "dev.sergiobelda.convention.spotless", version.ref = "sergiobelda-projectconfig" }

vanniktech-mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenpublish" }